import { readFile } from "node:fs/promises";

const RESET = "\x1b[0m";
const bold = (text) => `\x1b[1m${text}${RESET}`;
const italic = (text) => `\x1b[3m${text}${RESET}`;
// key/value colors from Firefox JSON Viewer.
const key = (text) => `\x1b[38;2;37;136;235m${text}${RESET}`;
const value = (text) => `\x1b[38;2;221;0;169m${text}${RESET}`;

/**
 * Report build issues for contributor spotlight files.
 *
 * This script is used by GitHub Actions to report issues found during the build process.
 *
 * @param {Object} params
 * @param {import('@actions/core')} params.core - GitHub Actions core library
 * @param {string} params.issuesPath - Path to the issues.json file generated by the build
 * @param {string} params.filesPath - Path to the contributor spotlight directory
 */
export async function reportIssues({ core, issuesPath, filesPath }) {

  const issuesByPath = JSON.parse(await readFile(issuesPath, "utf8"));

  for (const [filepath, issues] of Object.entries(issuesByPath)) {
    const prefix = filesPath.replace(/\/?$/, "/");

    if (!filepath.includes(prefix)) {
      continue;
    }

    const file = filepath.replace(prefix, "");
    const messages = [];

    for (const issue of issues) {
      const {
        source = "unknown",
        ...otherFields
      } = Object.fromEntries(issue.fields);

      const payload = Object.entries(otherFields)
        .map(([k, v]) => `${key(k)}: ${value(v)}`)
        .join(" • ");

      const message = source ? `${italic(`(${source})`)} ${payload}` : payload;
      messages.push(message);
    }

    const message = `Found ${bold(issues.length)} issue(s) in ${bold(file)}:\n${messages.join("\n")}`;
    core.warning(message, { file });
  }
};
