name: "General feedback"
description: Provide feedback on the target audience, general approach, high-level structure, usefulness, or anything else.
labels: ["general"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in a description of your feedback in the title field above
        ---
  - type: textarea
    id: problem
    attributes:
      label: Please describe your problem or observation
      description: This section should include a clear and concise description of what your problem or observation is.
      placeholder: e.g. I think the curriculum should include...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like to see
      description: This section should include a description of the changes you'll like to see made to the curriculum to fix the issue as you see it.
