name: "auto-merge"
on: [pull_request_target]

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  auto-merge:
    uses: mdn/workflows/.github/workflows/auto-merge.yml@main
    with:
      target-repo: "TODO: set this value to the name of the current (origin) repo"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
